version: '2'
services:
 mongo:
   image: registry.ng.bluemix.net/omslabservices/mongo
   container_name: mongo-chat-db
   expose: 
    - "27017"
 lets-chat-1:
   image: registry.ng.bluemix.net/omslabservices/lets-chat
   container_name: lets-chat-web-1
   expose: 
    - "8080"
    - "5222"
   links: 
    - mongo
   depends_on: 
     - mongo
   environment:
    - VCAP_SERVICES
 lets-chat-2:
   image: registry.ng.bluemix.net/omslabservices/lets-chat
   container_name: lets-chat-web-2
   expose:
    - "5222"
    - "8080"
    links:
     - mongo
    depends_on: 
     - mongo
   environment:
    - VCAP_SERVICES
 nginx:
   build:  nginx/
   container_name: lets-chat-nginx-1
   ports:
    - "80:80"
   links:
    - lets-chat-1
    - lets-chat-2
